#!/bin/sh
#searches google for given keywords
#usage ./google "(keywords)"
echo $1 > /home/abhinav/GoogleString 
python /abhinav/Projects/Bash/googleString.py #execute Python code that changes keywords to correct form
var=$(cat /home/abhinav/temp) #read results saved from Python code
xdg-open http://www.google.co.in/search?q=$var
rm /home/abhinav/temp
rm /home/abhinav/GoogleString

